[package]
name = "hand-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
tract-onnx = "0.21"
image = "0.25"
nokhwa = { version = "0.10", features = ["input-native"] }
minifb = "0.27"
imageproc = "0.25"